### ISSUE TITLE
update to v6.2

### ISSUE THREAD

**Issue by max75025** [duyplus/fontawesome-pro#5]
can you update repository to v6.2?

**Comment by duyplus** [comment]
Did you mean version 6.1.2 pro

**Comment by CCKNBC** [comment]
v6.2.0?

**Comment by duyplus** [comment]
> v6.2.0?

Yes, I updated it.

**Comment by IngXeneize** [comment]
Hi @duyplus, would you update it the otf's files to 6.2.x aswell? Thank you!!
